export interface Project {
  id: string;
  title: string;
  category: 'UI' | 'AI' | 'Experimental';
  description: string;
  coverImage: string;
  videoUrl?: string;
  process: string;
  gallery: string[];
}

export const PROJECTS: Project[] = [
  {
    id: '1',
    title: 'Neural Synthesis',
    category: 'AI',
    description: 'Exploring the intersection of latent space and architectural form.',
    coverImage: 'https://picsum.photos/seed/neural/1200/800',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-abstract-flowing-lines-of-light-3147-large.mp4',
    process: 'This project utilizes custom-trained Stable Diffusion models to generate architectural concepts that defy traditional structural logic. The goal was to visualize "living" buildings that respond to environmental data.',
    gallery: [
      'https://picsum.photos/seed/n1/800/600',
      'https://picsum.photos/seed/n2/800/600',
      'https://picsum.photos/seed/n3/800/600'
    ]
  },
  {
    id: '2',
    title: 'Aether OS',
    category: 'UI',
    description: 'A speculative operating system designed for spatial computing.',
    coverImage: 'https://picsum.photos/seed/os/1200/800',
    process: 'Aether OS reimagines the desktop metaphor for AR/VR environments. It focuses on depth, transparency, and gesture-based interaction, moving away from flat windows to volumetric widgets.',
    gallery: [
      'https://picsum.photos/seed/o1/800/600',
      'https://picsum.photos/seed/o2/800/600'
    ]
  },
  {
    id: '3',
    title: 'Kinetic Light',
    category: 'Experimental',
    description: 'An interactive installation mapping human motion to light patterns.',
    coverImage: 'https://picsum.photos/seed/kinetic/1200/800',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-digital-animation-of-a-blue-mesh-23340-large.mp4',
    process: 'Using LiDAR sensors and real-time generative shaders, Kinetic Light transforms physical movement into a digital aura. The installation explores the boundary between the physical body and digital representation.',
    gallery: [
      'https://picsum.photos/seed/k1/800/600',
      'https://picsum.photos/seed/k2/800/600'
    ]
  },
  {
    id: '4',
    title: 'Bio-Digital Interface',
    category: 'Experimental',
    description: 'Wearable tech that translates physiological data into generative art.',
    coverImage: 'https://picsum.photos/seed/bio/1200/800',
    process: 'This project explores the concept of "biological data as a medium". A wearable device tracks heart rate and skin conductance, which then drives a real-time visual system.',
    gallery: [
      'https://picsum.photos/seed/b1/800/600',
      'https://picsum.photos/seed/b2/800/600'
    ]
  },
  {
    id: '5',
    title: 'Flux UI Kit',
    category: 'UI',
    description: 'A high-performance design system for AI-first applications.',
    coverImage: 'https://picsum.photos/seed/flux/1200/800',
    process: 'Flux is a design system specifically built for LLM-driven interfaces. It prioritizes streaming states, dynamic content blocks, and context-aware navigation.',
    gallery: [
      'https://picsum.photos/seed/f1/800/600',
      'https://picsum.photos/seed/f2/800/600'
    ]
  },
  {
    id: '6',
    title: 'Latent Landscapes',
    category: 'AI',
    description: 'Generative environments created through GAN-based interpolation.',
    coverImage: 'https://picsum.photos/seed/latent/1200/800',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-abstract-video-of-a-blue-and-purple-smoke-32688-large.mp4',
    process: 'A series of infinite landscapes generated by traversing the latent space of a StyleGAN3 model trained on satellite imagery and abstract paintings.',
    gallery: [
      'https://picsum.photos/seed/l1/800/600',
      'https://picsum.photos/seed/l2/800/600'
    ]
  },
  {
    id: '7',
    title: 'Cognitive Canvas',
    category: 'AI',
    description: 'A shared virtual brain-mapping space powered by collaborative AI.',
    coverImage: 'https://picsum.photos/seed/cog/1200/800',
    process: 'Cognitive Canvas allows multiple users to brainwave-input ideas which the AI then clusters and visualizes in a 3D persistent space.',
    gallery: ['https://picsum.photos/seed/c1/800/600']
  },
  {
    id: '8',
    title: 'Prism Interface',
    category: 'UI',
    description: 'Dynamic light-refracting UI elements for high-end automotive displays.',
    coverImage: 'https://picsum.photos/seed/prism/1200/800',
    process: 'Design for next-gen electric vehicle dashboards, focusing on safety through minimal but high-intent visual cues.',
    gallery: ['https://picsum.photos/seed/p1/800/600']
  },
  {
    id: '9',
    title: 'Echo Location',
    category: 'Experimental',
    description: 'Visualizing invisible atmospheric data via AR spatial audio.',
    coverImage: 'https://picsum.photos/seed/echo/1200/800',
    process: 'An AR mobile app that makes air quality and signal strength "visible" as sonic architecture.',
    gallery: ['https://picsum.photos/seed/e1/800/600']
  },
  {
    id: '10',
    title: 'Synapse Core',
    category: 'AI',
    description: 'Real-time neural feedback visualization for clinical environments.',
    coverImage: 'https://picsum.photos/seed/syn/1200/800',
    process: 'Translating fMRI data into generative 3D particles to help patients visualize brain activity.',
    gallery: ['https://picsum.photos/seed/s1/800/600']
  },
  {
    id: '11',
    title: 'Void OS',
    category: 'UI',
    description: 'The first operating system designed for zero-distraction work.',
    coverImage: 'https://picsum.photos/seed/void/1200/800',
    process: 'A monochrome interface that uses timing and depth to prevent context switching.',
    gallery: ['https://picsum.photos/seed/v1/800/600']
  },
  {
    id: '12',
    title: 'Gravity Well',
    category: 'Experimental',
    description: 'A physical installation using magnets to simulate black hole behavior.',
    coverImage: 'https://picsum.photos/seed/grav/1200/800',
    process: 'A table-top kinetic sculpture where ferrofluids react to simulated gravitational fields.',
    gallery: ['https://picsum.photos/seed/g1/800/600']
  }
];
